version: '2.3'
services:
    frontend:
        build:
            context: ./frontend
        ports:
            - '4000:3000'
        volumes:
            - './frontend:/opt/app'
        environment:
            CI: 'true'
        restart: always
    backend:
        build:
            context: ./backend
        ports:
            - '4500:5000'
        volumes:
            - './backend:/opt/app'
        restart: always
